### ISSUE TITLE
shallow_water.jl

### ISSUE THREAD

**Issue by fxgiraldo** [JuliaLabs/ShallowWaterBench#10]
Hey guys, the shallow water looks pretty cool. One comment: you shouldn't need line 131. If I understand correctly, you are reimposing U=h*u but you have already evolved U in time correctly.

**Comment by fxgiraldo** [comment]
Hey guys, the shallow water looks pretty cool.  One comment: you shouldn't need line 131. If I understand correctly, you are reimposing U=h*u  but you have already evolved U in time correctly.

**Comment by peterahrens** [comment]
Thanks for the tip! I think I may have included that line because it was in the original shallow_water, but since it's not necessary I can remove it.
